### ISSUE TITLE
[BUG]: s6-supervise (child): fatal: unable to exec run: No such file or directory

### ISSUE THREAD

**Issue by dlach524** [norimicry/stardew-multiplayer-docker#14] opened 2024-04-20 04:14 UTC
**Describe the bug**
Unable to successfully run docker-compose  up

**To Reproduce**
1. git clone https://github.com/norimicry/stardew-multiplayer-docker.git
2. cd stardew-multiplayer-docker
3. docker-compose up
4. Once "starting utils" appears, start seeing error messages for unable to exec run: no such file or directory

**Expected behavior**
I expect the compose process to complete successfully and to be able to start up the server

**Logs**
```
F:\Games\Modding Stuff\Stardew>git clone https://github.com/norimicry/stardew-multiplayer-docker.git
Cloning into 'stardew-multiplayer-docker'...
remote: Enumerating objects: 510, done.
remote: Counting objects: 100% (355/355), done.
remote: Compressing objects: 100% (192/192), done.
remote: Total 510 (delta 171), reused 280 (delta 141), pack-reused 155
Receiving objects: 100% (510/510), 444.96 KiB | 4.41 MiB/s, done.
Resolving deltas: 100% (204/204), done.

F:\Games\Modding Stuff\Stardew>docker-compose up
no configuration file provided: not found

F:\Games\Modding Stuff\Stardew>cd stardew-multiplayer-docker

F:\Games\Modding Stuff\Stardew\stardew-multiplayer-docker>docker-compose up
time="2024-04-20T00:02:39-04:00" level=warning msg="F:\\Games\\Modding Stuff\\Stardew\\stardew-multiplayer-docker\\docker-compose.yml: `version` is obsolete"
2024/04/20 00:02:39 http2: server: error reading preface from client //./pipe/docker_engine: file has already been closed
[+] Building 0.0s (0/0)  docker:default
2024/04/20 00:02:39 http2: server: error reading preface from client //./pipe/docker_engine: file has already been close[+] Building 0.8s (18/18) FINISHED                                                                       docker:default
 => [valley internal] load build definition from Dockerfile                                                        0.0s
 => => transferring dockerfile: 1.81kB                                                                             0.0s
 => [valley internal] load metadata for docker.io/jlesage/baseimage-gui:debian-11                                  0.6s
 => [valley internal] load .dockerignore                                                                           0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [valley  1/13] FROM docker.io/jlesage/baseimage-gui:debian-11@sha256:dbf3ef5bab5680c5b51f2352e5a637971a0085ba  0.0s
 => [valley internal] load build context                                                                           0.0s
 => => transferring context: 528.63kB                                                                              0.0s
 => CACHED [valley  2/13] RUN apt-get update && apt-get install -y wget unzip tar strace mono-complete xterm gett  0.0s
 => CACHED [valley  3/13] RUN mkdir -p /data/Stardew &&     mkdir -p /data/nexus &&     wget --user-agent="Mozill  0.0s
 => CACHED [valley  4/13] RUN wget -qO dotnet.tar.gz https://download.visualstudio.microsoft.com/download/pr/d4b7  0.0s
 => CACHED [valley  5/13] RUN wget --user-agent="Mozilla" https://mirror.cloudcraft.info/SMAPI_latest.zip -qO /da  0.0s
 => CACHED [valley  6/13] COPY [mods/, /data/Stardew/game/Mods/]                                                   0.0s
 => CACHED [valley  7/13] COPY scripts/ /opt/                                                                      0.0s
 => CACHED [valley  8/13] RUN chmod +x /data/Stardew/game/StardewValley &&     chmod -R 777 /data/Stardew/ &&      0.0s
 => CACHED [valley  9/13] RUN mkdir /etc/services.d/utils && touch /etc/services.d/app/utils.dep                   0.0s
 => CACHED [valley 10/13] COPY run /etc/services.d/utils/run                                                       0.0s
 => CACHED [valley 11/13] RUN chmod +x /etc/services.d/utils/run                                                   0.0s
 => CACHED [valley 12/13] COPY docker-entrypoint.sh /startapp.sh                                                   0.0s
 => CACHED [valley 13/13] RUN chmod +x /startapp.sh                                                                0.0s
 => [valley] exporting to image                                                                                    0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:36565924f62b52cb4fe2ceb44cc4099c5cd9a742e3fb5aa29373aca1fe2c750b                       0.0s
 => => naming to docker.io/library/stardew-multiplayer-docker-valley                                               0.0s
[+] Running 1/2
 ✔ Network stardew-multiplayer-docker_default  Created                                                             0.0s
 - Container stardew                           Created                                                             0.1s
Attaching to stardew
stardew  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
stardew  | [s6-init] ensuring user provided files have correct perms...exited 0.
stardew  | [fix-attrs.d] applying ownership & permissions fixes...
stardew  | [fix-attrs.d] done.
stardew  | [cont-init.d] executing container initialization scripts...
stardew  | [cont-init.d] 00-app-niceness.sh: executing...
stardew  | [cont-init.d] 00-app-niceness.sh: exited 0.
stardew  | [cont-init.d] 00-app-script.sh: executing...
stardew  | [cont-init.d] 00-app-script.sh: exited 0.
stardew  | [cont-init.d] 00-app-user-map.sh: executing...
stardew  | [cont-init.d] 00-app-user-map.sh: exited 0.
stardew  | [cont-init.d] 00-clean-logmonitor-states.sh: executing...
stardew  | [cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
stardew  | [cont-init.d] 00-clean-tmp-dir.sh: executing...
stardew  | [cont-init.d] 00-clean-tmp-dir.sh: exited 0.
stardew  | [cont-init.d] 00-set-app-deps.sh: executing...
stardew  | [cont-init.d] 00-set-app-deps.sh: exited 0.
stardew  | [cont-init.d] 00-set-home.sh: executing...
stardew  | [cont-init.d] 00-set-home.sh: exited 0.
stardew  | [cont-init.d] 00-take-config-ownership.sh: executing...
stardew  | [cont-init.d] 00-take-config-ownership.sh: exited 0.
stardew  | [cont-init.d] 00-xdg-runtime-dir.sh: executing...
stardew  | [cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
stardew  | [cont-init.d] 10-certs.sh: executing...
stardew  | [cont-init.d] 10-certs.sh: exited 0.
stardew  | [cont-init.d] 10-cjk-font.sh: executing...
stardew  | [cont-init.d] 10-cjk-font.sh: exited 0.
stardew  | [cont-init.d] 10-nginx.sh: executing...
stardew  | [cont-init.d] 10-nginx.sh: exited 0.
stardew  | [cont-init.d] 10-vnc-password.sh: executing...
stardew  | stored passwd in file: /root/.vncpass
stardew  | [cont-init.d] 10-vnc-password.sh: exited 0.
stardew  | [cont-init.d] 10-web-index.sh: executing...
stardew  | [cont-init.d] 10-web-index.sh: exited 0.
stardew  | [cont-init.d] done.
stardew  | [services.d] starting services
stardew  | [services.d] starting s6-fdholderd...
stardew  | [services.d] starting nginx...
stardew  | [services.d] starting xvfb...
stardew  | [nginx] starting...
stardew  | [xvfb] starting...
stardew  | [services.d] starting utils...
stardew  | s6-supervise utils: warning: unable to spawn ./run - waiting 10 seconds
stardew  | s6-supervise (child): fatal: unable to exec run: No such file or directory
stardew  | s6-svwait: fatal: timed out
stardew  | [services.d] starting statusmonitor...
stardew  | [services.d] starting openbox...
stardew  | [statusmonitor] no file to monitor: disabling service...
stardew  | [openbox] starting...
stardew  | Openbox-Message: 04:02:46.193: Unable to make directory '/config/xdg/cache/openbox': Permission denied
stardew  | Openbox-Message: Unable to make directory "/config/xdg/cache/openbox/sessions": Permission denied
stardew  | [services.d] starting certsmonitor...
stardew  | [services.d] starting logmonitor...
stardew  | [services.d] starting x11vnc...
stardew  | [logmonitor] no file to monitor: disabling service...
stardew  | [certsmonitor] disabling service: secure connection not enabled.
stardew  | [services.d] starting app...
stardew  | [x11vnc] starting...
stardew  | 20/04/2024 04:02:48 passing arg to libvncserver: -rfbport
stardew  | 20/04/2024 04:02:48 passing arg to libvncserver: 5900
stardew  | 20/04/2024 04:02:48 passing arg to libvncserver: -rfbportv6
stardew  | 20/04/2024 04:02:48 passing arg to libvncserver: 5900
stardew  | 20/04/2024 04:02:48 passing arg to libvncserver: -desktop
stardew  | 20/04/2024 04:02:48 passing arg to libvncserver: StardewValley
stardew  | 20/04/2024 04:02:48 passing arg to libvncserver: -rfbauth
stardew  | 20/04/2024 04:02:48 passing arg to libvncserver: /root/.vncpass
stardew  | 20/04/2024 04:02:48 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 898
stardew  | [app] starting StardewValley...
stardew  | 20/04/2024 04:02:48 Using X display :0
stardew  | 20/04/2024 04:02:48 rootwin: 0x50e reswin: 0x400001 dpy: 0xbba7af50
stardew  | 20/04/2024 04:02:48
stardew  | 20/04/2024 04:02:48 ------------------ USEFUL INFORMATION ------------------
stardew  | [services.d] done.
stardew  | Configuring /data/Stardew/game/Mods/Always On Server/config.json
stardew  | Configuring /data/Stardew/game/Mods/AutoLoadGame/config.json
stardew  | Removing /data/Stardew/game/Mods/ChatCommands/ (ENABLE_CHATCOMMANDS_MOD=false)
stardew  | Removing /data/Stardew/game/Mods/ConsoleCommands/ (ENABLE_CONSOLECOMMANDS_MOD=false)
stardew  | Removing /data/Stardew/game/Mods/Crops Anytime Anywhere/ (ENABLE_CROPSANYTIMEANYWHERE_MOD=false)
stardew  | 20/04/2024 04:02:48 X DAMAGE available on display, using it for polling hints.
stardew  | 20/04/2024 04:02:48   To disable this behavior use: '-noxdamage'
stardew  | 20/04/2024 04:02:48
stardew  | 20/04/2024 04:02:48   Most compositing window managers like 'compiz' or 'beryl'
stardew  | 20/04/2024 04:02:48   cause X DAMAGE to fail, and so you may not see any screen
stardew  | 20/04/2024 04:02:48   updates via VNC.  Either disable 'compiz' (recommended) or
stardew  | 20/04/2024 04:02:48   supply the x11vnc '-noxdamage' command line option.
stardew  | 20/04/2024 04:02:48 X COMPOSITE available on display, using it for window polling.
stardew  | 20/04/2024 04:02:48   To disable this behavior use: '-noxcomposite'
stardew  | 20/04/2024 04:02:48
stardew  | 20/04/2024 04:02:48 Wireframing: -wireframe mode is in effect for window moves.
stardew  | 20/04/2024 04:02:48   If this yields undesired behavior (poor response, painting
stardew  | 20/04/2024 04:02:48   errors, etc) it may be disabled:
stardew  | 20/04/2024 04:02:48    - use '-nowf' to disable wireframing completely.
stardew  | 20/04/2024 04:02:48    - use '-nowcr' to disable the Copy Rectangle after the
stardew  | 20/04/2024 04:02:48      moved window is released in the new position.
stardew  | 20/04/2024 04:02:48   Also see the -help entry for tuning parameters.
stardew  | 20/04/2024 04:02:48   You can press 3 Alt_L's (Left "Alt" key) in a row to
stardew  | 20/04/2024 04:02:48   repaint the screen, also see the -fixscreen option for
stardew  | 20/04/2024 04:02:48   periodic repaints.
stardew  | Removing /data/Stardew/game/Mods/FriendsForever/ (ENABLE_FRIENDSFOREVER_MOD=false)
stardew  | 20/04/2024 04:02:48 GrabServer control via XTEST.
stardew  | Removing /data/Stardew/game/Mods/NoFenceDecay/ (ENABLE_NOFENCEDECAY_MOD=false)
stardew  | 20/04/2024 04:02:48
stardew  | 20/04/2024 04:02:48 Scroll Detection: -scrollcopyrect mode is in effect to
stardew  | 20/04/2024 04:02:48   use RECORD extension to try to detect scrolling windows
stardew  | 20/04/2024 04:02:48   (induced by either user keystroke or mouse input).
stardew  | 20/04/2024 04:02:48   If this yields undesired behavior (poor response, painting
stardew  | 20/04/2024 04:02:48   errors, etc) it may be disabled via: '-noscr'
stardew  | 20/04/2024 04:02:48   Also see the -help entry for tuning parameters.
stardew  | 20/04/2024 04:02:48   You can press 3 Alt_L's (Left "Alt" key) in a row to
stardew  | 20/04/2024 04:02:48   repaint the screen, also see the -fixscreen option for
stardew  | 20/04/2024 04:02:48   periodic repaints.
stardew  | 20/04/2024 04:02:48
stardew  | 20/04/2024 04:02:48 XKEYBOARD: number of keysyms per keycode 7 is greater
stardew  | 20/04/2024 04:02:48   than 4 and 51 keysyms are mapped above 4.
stardew  | 20/04/2024 04:02:48   Automatically switching to -xkb mode.
stardew  | 20/04/2024 04:02:48   If this makes the key mapping worse you can
stardew  | 20/04/2024 04:02:48   disable it with the "-noxkb" option.
stardew  | 20/04/2024 04:02:48   Also, remember "-remap DEAD" for accenting characters.
stardew  | 20/04/2024 04:02:48
stardew  | 20/04/2024 04:02:48 X FBPM extension not supported.
stardew  | Xlib:  extension "DPMS" missing on display ":0".
stardew  | 20/04/2024 04:02:48 X display is not capable of DPMS.
stardew  | 20/04/2024 04:02:48 --------------------------------------------------------
stardew  | 20/04/2024 04:02:48
stardew  | 20/04/2024 04:02:48 Default visual ID: 0x21
stardew  | Removing /data/Stardew/game/Mods/NonDestructiveNPCs/ (ENABLE_NONDESTRUCTIVENPCS_MOD=false)
stardew  | 20/04/2024 04:02:48 Read initial data from X display into framebuffer.
stardew  | 20/04/2024 04:02:48 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/4800
stardew  | 20/04/2024 04:02:48
stardew  | 20/04/2024 04:02:48 X display :0 is 32bpp depth=24 true color
stardew  | 20/04/2024 04:02:48
stardew  | 20/04/2024 04:02:48 Listening for VNC connections on TCP port 5900
stardew  | 20/04/2024 04:02:48 Listening for VNC connections on TCP6 port 5900
stardew  | 20/04/2024 04:02:48 listen6: bind: Address already in use
stardew  | 20/04/2024 04:02:48 Not listening on IPv6 interface.
stardew  | 20/04/2024 04:02:48
stardew  | 20/04/2024 04:02:48 Xinerama is present and active (e.g. multi-head).
stardew  | 20/04/2024 04:02:48 Xinerama: number of sub-screens: 1
stardew  | 20/04/2024 04:02:48 Xinerama: no blackouts needed (only one sub-screen)
stardew  | 20/04/2024 04:02:48
stardew  | Removing /data/Stardew/game/Mods/TimeSpeed/ (ENABLE_TIMESPEED_MOD=false)
stardew  | 20/04/2024 04:02:48 fb read rate: 3532 MB/sec
stardew  | 20/04/2024 04:02:48 fast read: reset -wait  ms to: 10
stardew  | 20/04/2024 04:02:48 fast read: reset -defer ms to: 10
stardew  | 20/04/2024 04:02:48 The X server says there are 10 mouse buttons.
stardew  | 20/04/2024 04:02:48 screen setup finished.
stardew  | 20/04/2024 04:02:48
stardew  |
stardew  | The VNC desktop is:      bcf5bf43b65e:0
stardew  | PORT=5900
stardew  |
stardew  | ******************************************************************************
stardew  | Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?
stardew  |
stardew  | The scheme stores pixel data offscreen on the VNC viewer side for faster
stardew  | retrieval.  It should work with any VNC viewer.  Try it by running:
stardew  |
stardew  |     x11vnc -ncache 10 ...
stardew  |
stardew  | One can also add -ncache_cr for smooth 'copyrect' window motion.
stardew  | More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching
stardew  |
stardew  | -- SMAPI Log: Starting
stardew  | -- SMAPI Log: Waiting for log to appear
stardew  | Running Stardew Valley
stardew  | /usr/bin/xterm
stardew  | s6-supervise (child): fatal: unable to exec run: No such file or directory
stardew  | s6-supervise utils: warning: unable to spawn ./run - waiting 10 seconds
stardew  | -- SMAPI Log:  Tailing
stardew  | [04:02:52 DEBUG SMAPI] Launching mods...
stardew  | [04:02:52 TRACE Save Backup] No saves found.
stardew  | [04:02:52 DEBUG SMAPI] Mods loaded and ready!
stardew  | [04:02:52 TRACE SMAPI] Checking for updates...
stardew  | [04:02:52 TRACE game] setGameMode( 'titleScreenGameMode (0)' )
stardew  | [04:02:52 TRACE game] path '/config/xdg/config/StardewValley/startup_preferences' did not exist and will be created in Docker Desktop   w Enable Watch
stardew  | [04:02:52 ALERT SMAPI] You can update SMAPI to 4.0.7: https://smapi.io
stardew  | [04:02:52 TRACE SMAPI]    Checking for updates to 2 mods...
stardew  | [04:02:52 TRACE SMAPI]    All mods up to date.
stardew  | [04:02:52 INFO  SMAPI] Type 'help' for help, or 'help <cmd>' for a command's usage
stardew  | s6-supervise (child): fatal: unable to exec run: No such file or directory
stardew  | s6-supervise utils: warning: unable to spawn ./run - waiting 10 seconds
stardew  | s6-supervise (child): fatal: unable to exec run: No such file or directory
stardew  | s6-supervise utils: warning: unable to spawn ./run - waiting 10 seconds
stardew  | s6-supervise (child): fatal: unable to exec run: No such file or directory
stardew  | s6-supervise utils: warning: unable to spawn ./run - waiting 10 seconds
stardew  | s6-supervise (child): fatal: unable to exec run: No such file or directory
stardew  | s6-supervise utils: warning: unable to spawn ./run - waiting 10 seconds
Gracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1 Desktop   w Enable Watch
 ✔ Container stardew  Stopped                                                                                      3.6s
canceled

F:\Games\Modding Stuff\Stardew\stardew-multiplayer-docker>
```

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro Version 22H2 Build 22621.3447

**Additional context**
Steam: Stardew Valley V1.6.5 build 24110

**Comment by cavazos-apps** [comment] 2024-04-20 14:34
Please provide the output of ```git config --get core.autocrlf```.

**Comment by dlach524** [comment] 2024-04-20 15:06
> Please provide the output of `git config --get core.autocrlf`.

```
F:\Games\Modding Stuff\Stardew\stardew-multiplayer-docker>git config --get core.autocrlf
true
```

**Comment by cavazos-apps** [comment] 2024-04-20 15:09
Try setting it to ```input``` by using ```git config --global core.autocrlf input``` and deleting + re-cloning the repository. I suspect the issue is Windows line-endings. I tried to adjust this automatically but suspect that isn't working as expected.

**Comment by dlach524** [comment] 2024-04-20 15:24
Same result:
```
F:\Games\Modding Stuff\Stardew>git config --get core.autocrlf
input

F:\Games\Modding Stuff\Stardew>rmdir /S stardew-multiplayer-docker
stardew-multiplayer-docker, Are you sure (Y/N)? y

F:\Games\Modding Stuff\Stardew>git clone https://github.com/norimicry/stardew-multiplayer-docker.git
Cloning into 'stardew-multiplayer-docker'...
remote: Enumerating objects: 510, done.
remote: Counting objects: 100% (355/355), done.
remote: Compressing objects: 100% (193/193), done.
remote: Total 510 (delta 171), reused 279 (delta 140), pack-reused 155
Receiving objects: 100% (510/510), 445.02 KiB | 3.77 MiB/s, done.
Resolving deltas: 100% (204/204), done.

F:\Games\Modding Stuff\Stardew>cd stardew-multiplayer-docker

F:\Games\Modding Stuff\Stardew\stardew-multiplayer-docker>docker-compose up
time="2024-04-20T11:22:19-04:00" level=warning msg="F:\\Games\\Modding Stuff\\Stardew\\stardew-multiplayer-docker\\docker-compose.yml: `version` is obsolete"
[+] Running 1/0
 ✔ Container stardew  Created                                                                                      0.0s
Attaching to stardew
stardew  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
stardew  | [s6-init] ensuring user provided files have correct perms...exited 0.
stardew  | [fix-attrs.d] applying ownership & permissions fixes...
stardew  | [fix-attrs.d] done.
stardew  | [cont-init.d] executing container initialization scripts...
stardew  | [cont-init.d] 00-app-niceness.sh: executing...
stardew  | [cont-init.d] 00-app-niceness.sh: exited 0.
stardew  | [cont-init.d] 00-app-script.sh: executing...
stardew  | [cont-init.d] 00-app-script.sh: exited 0.
stardew  | [cont-init.d] 00-app-user-map.sh: executing...
stardew  | [cont-init.d] 00-app-user-map.sh: exited 0.
stardew  | [cont-init.d] 00-clean-logmonitor-states.sh: executing...
stardew  | [cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
stardew  | [cont-init.d] 00-clean-tmp-dir.sh: executing...
stardew  | [cont-init.d] 00-clean-tmp-dir.sh: exited 0.
stardew  | [cont-init.d] 00-set-app-deps.sh: executing...
stardew  | [cont-init.d] 00-set-app-deps.sh: exited 0.
stardew  | [cont-init.d] 00-set-home.sh: executing...
stardew  | [cont-init.d] 00-set-home.sh: exited 0.
stardew  | [cont-init.d] 00-take-config-ownership.sh: executing...
stardew  | [cont-init.d] 00-take-config-ownership.sh: exited 0.
stardew  | [cont-init.d] 00-xdg-runtime-dir.sh: executing...
stardew  | [cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
stardew  | [cont-init.d] 10-certs.sh: executing...
stardew  | [cont-init.d] 10-certs.sh: exited 0.
stardew  | [cont-init.d] 10-cjk-font.sh: executing...
stardew  | [cont-init.d] 10-cjk-font.sh: exited 0.
stardew  | [cont-init.d] 10-nginx.sh: executing...
stardew  | [cont-init.d] 10-nginx.sh: exited 0.
stardew  | [cont-init.d] 10-vnc-password.sh: executing...
stardew  | stored passwd in file: /root/.vncpass
stardew  | [cont-init.d] 10-vnc-password.sh: exited 0.
stardew  | [cont-init.d] 10-web-index.sh: executing...
stardew  | [cont-init.d] 10-web-index.sh: exited 0.
stardew  | [cont-init.d] done.
stardew  | [services.d] starting services
stardew  | [services.d] starting s6-fdholderd...
stardew  | [services.d] starting nginx...
stardew  | [services.d] starting xvfb...
stardew  | [nginx] starting...
stardew  | [xvfb] starting...
stardew  | [services.d] starting utils...
stardew  | s6-supervise (child): fatal: unable to exec run: No such file or directory
stardew  | s6-supervise utils: warning: unable to spawn ./run - waiting 10 seconds
stardew  | s6-svwait: fatal: timed out
```

**Comment by cavazos-apps** [comment] 2024-04-20 15:52
It may have used the previous container as well. Execute ```docker compose build --no-cache``` prior to ```docker compose up```.

**Comment by dlach524** [comment] 2024-04-20 16:22
Thanks, that did the trick and I'm not getting the errors anymore! Pesky line-endings! Now I'll try to figure out why I'm just getting a black screen when connecting via web or TightVNC... might have a few things to check on my side.

**Comment by Z3roX** [comment] 2024-04-20 16:33
> Thanks, that did the trick and I'm not getting the errors anymore! Pesky line-endings! Now I'll try to figure out why I'm just getting a black screen when connecting via web of TightVNC... might have a few things to check on my side.

Same problem here

**Comment by cavazos-apps** [comment] 2024-04-22 21:26
@dlach524 See [here](https://github.com/norimicry/stardew-multiplayer-docker/issues/12#issuecomment-2070976657). I may have fixed the black screen issue. It was unrelated to your issue and may have been a SMAPI issue.

**Comment by cavazos-apps** [comment] 2024-04-22 23:52
Closing this as we are tracking the effort in #12.

**Closed as completed by cavazos-apps** 2024-04-22 23:52 UTC
Labels: bug
